name: planner_challenger_student
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
